# ===== build =====
FROM node:24-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# ===== runtime =====
FROM node:24-alpine AS runtime

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY --from=build /app/dist ./dist

CMD ["npm", "run", "preview"]